import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';
import { PointerLockControls } from 'https://cdn.jsdelivr.net/npm/three@0.180.0/examples/jsm/controls/PointerLockControls.js';

const scene=new THREE.Scene();scene.background=new THREE.Color(0x8ab5d6);scene.fog=new THREE.FogExp2(0x8ab5d6,.009);
const camera=new THREE.PerspectiveCamera(68,innerWidth/innerHeight,.1,1200);camera.position.set(0,4,9);
const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;document.body.appendChild(renderer.domElement);
scene.add(new THREE.HemisphereLight(0xcce8ff,0x1a2330,2.2));const sun=new THREE.DirectionalLight(0xfff1d1,4);sun.position.set(-80,120,50);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);scene.add(sun);
const ground=new THREE.Mesh(new THREE.PlaneGeometry(1000,1000),new THREE.MeshStandardMaterial({color:0x26352b,roughness:.92,metalness:0}));ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;scene.add(ground);
const roadMat=new THREE.MeshStandardMaterial({color:0x11151b,roughness:.75});const sidewalkMat=new THREE.MeshStandardMaterial({color:0x51575c,roughness:1});
for(let x=-180;x<=180;x+=36){let r=new THREE.Mesh(new THREE.BoxGeometry(10,.12,1000),roadMat);r.position.set(x,.06,0);scene.add(r);for(let z=-480;z<480;z+=24){let line=new THREE.Mesh(new THREE.BoxGeometry(.25,.03,7),new THREE.MeshBasicMaterial({color:0xf4d66d}));line.position.set(x,.13,z);scene.add(line)}}
for(let z=-180;z<=180;z+=36){let r=new THREE.Mesh(new THREE.BoxGeometry(1000,.12,10),roadMat);r.position.set(0,.06,z);scene.add(r)}
function building(x,z,w,d,h,c){const m=new THREE.MeshStandardMaterial({color:c,roughness:.58,metalness:.12});const b=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),m);b.position.set(x,h/2,z);b.castShadow=b.receiveShadow=true;scene.add(b);const rows=Math.max(2,Math.floor(h/3));const cols=Math.max(2,Math.floor(w/3));const win=new THREE.MeshBasicMaterial({color:0xa7dcff});for(let y=2;y<h-1;y+=3){for(let i=0;i<cols;i++){let q=new THREE.Mesh(new THREE.BoxGeometry(.7,.9,.035),win);q.position.set(x-w/2+2+i*3,y,z-d/2-.02);scene.add(q)}}}
const colors=[0x17212b,0x222b36,0x343a40,0x142d3d,0x3a3029];for(let x=-160;x<=160;x+=24)for(let z=-160;z<=160;z+=24)if(Math.abs(x%36)>1&&Math.abs(z%36)>1)building(x,z,18+Math.random()*8,18+Math.random()*8,18+Math.random()*65,colors[Math.floor(Math.random()*colors.length)]);
// Ma'Kyren: original biracial protagonist
const player=new THREE.Group();const skin=new THREE.MeshStandardMaterial({color:0x9a6549,roughness:.65});const shirt=new THREE.MeshStandardMaterial({color:0x10131a,roughness:.5});const pants=new THREE.MeshStandardMaterial({color:0x171b24,roughness:.75});
const torso=new THREE.Mesh(new THREE.CapsuleGeometry(.62,1.25,6,12),shirt);torso.position.y=2.05;torso.castShadow=true;player.add(torso);const head=new THREE.Mesh(new THREE.SphereGeometry(.48,24,16),skin);head.position.y=3.35;head.scale.set(1,.95,.9);head.castShadow=true;player.add(head);const legs=[];for(const x of[-.32,.32]){let l=new THREE.Mesh(new THREE.CapsuleGeometry(.22,1.05,5,10),pants);l.position.set(x,.72,0);l.castShadow=true;player.add(l);legs.push(l)}const hair=new THREE.Mesh(new THREE.SphereGeometry(.5,20,12),new THREE.MeshStandardMaterial({color:0x17120f,roughness:.9}));hair.position.set(0,3.63,-.02);hair.scale.set(1,.55,1);hair.castShadow=true;player.add(hair);scene.add(player);
// vehicle fleet
function car(x,z,color=0x183e67){const g=new THREE.Group();const body=new THREE.Mesh(new THREE.BoxGeometry(2.1,.65,4.3),new THREE.MeshStandardMaterial({color,metalness:.65,roughness:.28}));body.position.y=.72;body.castShadow=true;g.add(body);const cabin=new THREE.Mesh(new THREE.BoxGeometry(1.7,.65,2.1),new THREE.MeshStandardMaterial({color:0x111a22,metalness:.15,roughness:.1,transparent:true,opacity:.92}));cabin.position.y=1.25;g.add(cabin);for(const dx of[-1.1,1.1])for(const dz of[-1.45,1.45]){const w=new THREE.Mesh(new THREE.CylinderGeometry(.34,.34,.2,20),new THREE.MeshStandardMaterial({color:0x080909,roughness:.8}));w.rotation.z=Math.PI/2;w.position.set(dx,0.45,dz);g.add(w)}g.position.set(x,0,z);scene.add(g)}for(let i=0;i<26;i++)car((Math.random()-.5)*300,(Math.random()-.5)*300,[0x0d5c8b,0x8c2020,0xd3b84b,0xdddddd,0x101010][i%5]);
const controls=new PointerLockControls(camera,renderer.domElement);let keys={},vel=new THREE.Vector3(),onGround=true;addEventListener('keydown',e=>keys[e.code]=true);addEventListener('keyup',e=>keys[e.code]=false);renderer.domElement.addEventListener('click',()=>{if(innerWidth>800)controls.lock()});
let joy={x:0,y:0};const stick=document.getElementById('stick'),knob=document.getElementById('knob');stick.addEventListener('pointermove',e=>{if(e.buttons!==1)return;const r=stick.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2;let x=e.clientX-cx,y=e.clientY-cy;const d=Math.hypot(x,y),m=45;if(d>m){x=x/d*m;y=y/d*m}knob.style.transform=`translate(${x}px,${y}px)`;joy.x=x/m;joy.y=y/m});stick.addEventListener('pointerup',()=>{joy.x=joy.y=0;knob.style.transform=''});
document.getElementById('jump').addEventListener('pointerdown',()=>{if(onGround){vel.y=9;onGround=false}});let sprint=false;document.getElementById('run').addEventListener('pointerdown',()=>sprint=!sprint);
const clock=new THREE.Clock();function animate(){requestAnimationFrame(animate);const dt=Math.min(clock.getDelta(),.05);let f=(keys.KeyW?1:0)-(keys.KeyS?1:0)-joy.y,r=(keys.KeyD?1:0)-(keys.KeyA?1:0)+joy.x;if(f||r){const speed=sprint?12:6;const dir=new THREE.Vector3(r,0,f).normalize().multiplyScalar(speed*dt);player.position.x+=dir.x;player.position.z+=dir.z;player.rotation.y=Math.atan2(dir.x,dir.z)}vel.y-=25*dt;player.position.y+=vel.y*dt;if(player.position.y<=0){player.position.y=0;vel.y=0;onGround=true}camera.position.lerp(new THREE.Vector3(player.position.x,player.position.y+5.2,player.position.z+8.5),.12);camera.lookAt(player.position.x,player.position.y+2,player.position.z);renderer.render(scene,camera)}animate();setTimeout(()=>{document.getElementById('loading').style.opacity=0;setTimeout(()=>document.getElementById('loading').remove(),700)},900);addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
