import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';
import { applyCinematicVisuals } from './visual_quality.js';
const mobile=/Android|iPhone|iPad|iPod/i.test(navigator.userAgent)||innerWidth<900;
const scene=new THREE.Scene(), camera=new THREE.PerspectiveCamera(65,innerWidth/innerHeight,.1,1400);
const renderer=new THREE.WebGLRenderer({antialias:!mobile,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,mobile?1.2:1.65));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;document.body.appendChild(renderer.domElement);applyCinematicVisuals(renderer,scene,camera);
scene.add(new THREE.HemisphereLight(0xd9edff,0x19222b,2));const sun=new THREE.DirectionalLight(0xffe6bb,4);sun.position.set(-100,140,60);sun.castShadow=true;sun.shadow.mapSize.set(mobile?1024:2048,mobile?1024:2048);scene.add(sun);
const ground=new THREE.Mesh(new THREE.PlaneGeometry(1200,1200),new THREE.MeshStandardMaterial({color:0x26362c,roughness:.96}));ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;scene.add(ground);
const road=new THREE.MeshStandardMaterial({color:0x11151a,roughness:.82});for(let x=-180;x<=180;x+=36){const r=new THREE.Mesh(new THREE.BoxGeometry(10,.12,1100),road);r.position.set(x,.06,0);scene.add(r);for(let z=-500;z<500;z+=24){const l=new THREE.Mesh(new THREE.BoxGeometry(.18,.025,7),new THREE.MeshBasicMaterial({color:0xf0cf68}));l.position.set(x,.13,z);scene.add(l)}}
const buildingColors=[0x17212b,0x242d37,0x343a40,0x153246,0x3a3029];for(let x=-160;x<=160;x+=24)for(let z=-160;z<=160;z+=24){if(x%36===0||z%36===0)continue;const w=18+Math.random()*8,d=18+Math.random()*8,h=18+Math.random()*65;const b=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),new THREE.MeshStandardMaterial({color:buildingColors[Math.floor(Math.random()*buildingColors.length)],roughness:.62,metalness:.1}));b.position.set(x,h/2,z);b.castShadow=b.receiveShadow=true;scene.add(b);for(let y=4;y<h-2;y+=4){const n=Math.max(1,Math.floor(w/3));for(let i=0;i<n;i++){const win=new THREE.Mesh(new THREE.BoxGeometry(.72,.9,.035),new THREE.MeshBasicMaterial({color:0x9bd7ff}));win.position.set(x-w/2+2+i*3,y,z-d/2-.025);scene.add(win)}}}
const player=new THREE.Group();const skin=new THREE.MeshStandardMaterial({color:0x9a6549,roughness:.6}),clothes=new THREE.MeshStandardMaterial({color:0x111722,roughness:.5});const body=new THREE.Mesh(new THREE.CapsuleGeometry(.62,1.15,8,16),clothes);body.position.y=2.15;body.castShadow=true;player.add(body);const head=new THREE.Mesh(new THREE.SphereGeometry(.49,24,16),skin);head.position.y=3.42;player.add(head);const hair=new THREE.Mesh(new THREE.SphereGeometry(.51,20,12),new THREE.MeshStandardMaterial({color:0x120f0e,roughness:.9}));hair.position.y=3.67;hair.scale.set(1,.55,1);player.add(hair);scene.add(player);
const cars=[];for(let i=0;i<(mobile?14:24);i++){const g=new THREE.Group(),c=[0x0d5c8b,0x8c2020,0xd3b84b,0xdddddd,0x101010][i%5];const m=new THREE.MeshStandardMaterial({color:c,metalness:.6,roughness:.3});const b=new THREE.Mesh(new THREE.BoxGeometry(2.1,.65,4.3),m);b.position.y=.72;b.castShadow=true;g.add(b);const cab=new THREE.Mesh(new THREE.BoxGeometry(1.7,.65,2.1),new THREE.MeshStandardMaterial({color:0x111a22,roughness:.1,metalness:.15}));cab.position.y=1.25;g.add(cab);g.position.set((Math.random()-.5)*300,0,(Math.random()-.5)*300);g.userData.speed=4+Math.random()*3;scene.add(g);cars.push(g)}
const clock=new THREE.Clock();let yaw=Math.PI,pitch=.2,drag=false,lx=0,ly=0;addEventListener('pointerdown',e=>{if(e.target===renderer.domElement){drag=true;lx=e.clientX;ly=e.clientY}});addEventListener('pointerup',()=>drag=false);addEventListener('pointermove',e=>{if(!drag)return;yaw-=(e.clientX-lx)*.006;pitch=Math.max(-.1,Math.min(.7,pitch-(e.clientY-ly)*.004));lx=e.clientX;ly=e.clientY});
const keys={};addEventListener('keydown',e=>keys[e.code]=true);addEventListener('keyup',e=>keys[e.code]=false);
function loop(){requestAnimationFrame(loop);const dt=Math.min(clock.getDelta(),.05);const f=(keys.KeyW?1:0)-(keys.KeyS?1:0),r=(keys.KeyD?1:0)-(keys.KeyA?1:0);if(f||r){const n=Math.hypot(f,r),s=6*dt,sy=Math.sin(yaw),cy=Math.cos(yaw);player.position.x+=(r/n*cy+f/n*sy)*s;player.position.z+=(r/n*sy-f/n*cy)*s}for(const v of cars){v.translateZ(-v.userData.speed*dt);if(v.position.z<-180)v.position.z=180}const dist=9,cp=Math.cos(pitch),sp=Math.sin(pitch);camera.position.lerp(new THREE.Vector3(player.position.x+Math.sin(yaw)*dist*cp,player.position.y+3.5+dist*sp,player.position.z+Math.cos(yaw)*dist*cp),.12);camera.lookAt(player.position.x,player.position.y+2,player.position.z);renderer.render(scene,camera)}loop();
setTimeout(()=>document.getElementById('loading')?.remove(),1200);addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});