import { Engine, Scene, ArcRotateCamera, Vector3, TransformNode, HemisphericLight, DirectionalLight, PointLight, SpotLight, ShadowGenerator, Color4, MeshBuilder, StandardMaterial, Color3, PBRMaterial, Texture, GlowLayer, ShaderMaterial, Effect } from '@babylonjs/core';
import '@babylonjs/loaders/glTF';
import { SceneLoader } from '@babylonjs/core/Loading/sceneLoader';
import { DynamicTexture } from '@babylonjs/core/Materials/Textures/dynamicTexture';
import { DefaultRenderingPipeline } from '@babylonjs/core/PostProcesses/RenderPipeline/Pipelines/defaultRenderingPipeline';
import { ColorCurves } from '@babylonjs/core/Materials/colorCurves';
import { SSRRenderingPipeline } from '@babylonjs/core/PostProcesses/RenderPipeline/Pipelines/ssrRenderingPipeline';

const canvas=document.getElementById('renderCanvas'); const materialRoot='/makyren_gta_game/visual-004/assets/materials/'; const loadMaterialTexture=(path,scale=1)=>{const texture=new Texture(materialRoot+path,scene,false,false);texture.uScale=scale;texture.vScale=scale;return texture;};
const params=new URLSearchParams(location.search); const qualityParam=params.get('quality'); const debug=params.get('debug')==='1';
const quality=qualityParam||((innerWidth<720||navigator.hardwareConcurrency<4)?'mobile':'high');
const qualityConfig={mobile:{scale:1.55,glow:.25,windows:false,camera:30,shadows:false},medium:{scale:1.2,glow:.45,windows:true,camera:27,shadows:false},high:{scale:.85,glow:.7,windows:true,camera:24,shadows:true}}[quality]||{scale:.85,glow:.7,windows:true,camera:24,shadows:true};
const engine=new Engine(canvas,true,{preserveDrawingBuffer:false,stencil:true},true); engine.setHardwareScalingLevel(qualityConfig.scale);
window.MakyrenVisualQuality={preset:quality,config:qualityConfig};
window.MakyrenAssetSlots={character:'assets/makyren.glb',vehicle:'assets/hero_vehicle.glb',buildings:'assets/city-kit.glb',props:'assets/street-props.glb',streetLamp:'assets/street_lamp_01.glb',tree:'assets/tree_small_02.glb'};
window.MakyrenLoadAsset=async(slot,{autoAdd=true}={})=>{const path=window.MakyrenAssetSlots[slot];if(!path)throw new Error(`Unknown asset slot: ${slot}`);try{const container=await SceneLoader.LoadAssetContainerAsync('',path,scene);if(autoAdd)container.addAllToScene();return {slot,path,container,loaded:true};}catch(error){console.warn(`Optional asset ${slot} unavailable; procedural fallback remains active.`,error);return {slot,path,loaded:false,fallback:true};}};
const scene=new Scene(engine); scene.clearColor=new Color4(.018,.028,.05,1); scene.fogMode=Scene.FOGMODE_EXP2; scene.fogDensity=quality==='mobile'?.014:quality==='medium'?.009:.0065; scene.fogStart=10; scene.fogColor=new Color3(.018,.028,.05); scene.imageProcessingConfiguration.toneMappingEnabled=true; scene.imageProcessingConfiguration.toneMappingType=Scene.TONEMAPPING_ACES; scene.imageProcessingConfiguration.exposure=1.12; scene.imageProcessingConfiguration.contrast=1.18; const glow=new GlowLayer('cinematic_glow',scene); glow.intensity=qualityConfig.glow; glow.blurKernel=quality==='high'?32:16;
const camera=new ArcRotateCamera('camera',-Math.PI/2.5,1.34,qualityConfig.camera,new Vector3(0,1.2,0),scene);
camera.inputs.clear(); camera.wheelPrecision=80; camera.lowerRadiusLimit=6; camera.upperRadiusLimit=45; camera.minZ=.1; camera.alpha=-Math.PI/2.5; camera.beta=1.34; scene.activeCamera=camera; const post=new DefaultRenderingPipeline('visual_post',true,scene,[camera]);post.fxaaEnabled=true;post.samples=quality==='high'?2:1;post.bloomEnabled=quality!=='mobile';post.bloomThreshold=.78;post.bloomWeight=quality==='high'?.22:.14;post.bloomKernel=quality==='high'?48:24;post.imageProcessingEnabled=true;post.imageProcessing.toneMappingEnabled=true;post.imageProcessing.toneMappingType=Scene.TONEMAPPING_ACES;post.imageProcessing.exposure=1.08;post.imageProcessing.contrast=1.22;const grade=new ColorCurves();grade.globalHue=218;grade.globalSaturation=8;grade.globalDensity=2;grade.highlightsHue=38;grade.highlightsSaturation=12;grade.highlightsDensity=3;grade.shadowsHue=220;grade.shadowsSaturation=10;grade.shadowsDensity=-2;scene.imageProcessingConfiguration.colorCurves=grade;scene.imageProcessingConfiguration.colorCurvesEnabled=true;const ssr=quality==='high'&&params.get('ssr')==='1'?new SSRRenderingPipeline('screen_space_reflections',scene,[camera],true):null;if(ssr){ssr.isEnabled=true;ssr.maxDistance=10;ssr.step=1;ssr.maxSteps=32;ssr.thickness=.12;ssr.reflectionSpecularFalloffExponent=2.2;ssr.ssrDownsample=1;ssr.blurDispersionStrength=0;ssr.blurDownsample=1;ssr.enableSmoothReflections=false;ssr.useFresnel=false;ssr.attenuateScreenBorders=true;ssr.attenuateIntersectionDistance=true;}window.MakyrenPostFX={bloom:post.bloomEnabled,ssr:Boolean(ssr),ssrOptIn:'?ssr=1',colorCurves:true,ssrBudget:ssr?{maxSteps:ssr.maxSteps,downsample:ssr.ssrDownsample}:null};
const skyLight=new HemisphericLight('sky',new Vector3(0,1,0),scene); skyLight.intensity=1.45;skyLight.diffuse=new Color3(.22,.32,.55);skyLight.groundColor=new Color3(.035,.045,.075);
const sun=new DirectionalLight('sun',new Vector3(-0.45,-1,0.35),scene); sun.intensity=2.6; sun.position=new Vector3(30,45,-25); const heroKey=new SpotLight('hero_key',new Vector3(-5,7,-12),new Vector3(.25,-.72,1),Math.PI/3.2,2.4,scene);heroKey.diffuse=new Color3(1,.34,.12);heroKey.specular=new Color3(1,.55,.25);heroKey.intensity=quality==='mobile'?1.2:2.4;heroKey.range=24;const cityRim=new DirectionalLight('city_rim',new Vector3(.35,-.4,-.65),scene);cityRim.diffuse=new Color3(.08,.2,.52);cityRim.specular=new Color3(.12,.25,.6);cityRim.intensity=.7; const shadowGenerator=qualityConfig.shadows?new ShadowGenerator(1024,sun):null; if(shadowGenerator){shadowGenerator.useBlurExponentialShadowMap=true;shadowGenerator.blurKernel=24;shadowGenerator.bias=.0005;}
const road=MeshBuilder.CreateGround('road',{width:18,height:80},scene);
const roadMat=new PBRMaterial('asphalt',scene); roadMat.albedoColor=new Color3(.035,.042,.05); roadMat.metallic=.08; roadMat.roughness=.72; roadMat.environmentIntensity=.32; if(quality!=='mobile'){roadMat.albedoTexture=loadMaterialTexture('asphalt/color.jpg',4);roadMat.bumpTexture=loadMaterialTexture('asphalt/normal.jpg',4);roadMat.roughnessTexture=loadMaterialTexture('asphalt/roughness.jpg',4);roadMat.ambientTexture=loadMaterialTexture('asphalt/ao.jpg',4);} road.material=roadMat; road.receiveShadows=true;
const sidewalkMat=new PBRMaterial('sidewalk',scene); sidewalkMat.albedoColor=new Color3(.24,.25,.24); sidewalkMat.roughness=.9;
for(const x of [-11,11]){const s=MeshBuilder.CreateGround('sidewalk',{width:4,height:80},scene);s.position.x=x;s.material=sidewalkMat;s.receiveShadows=true;}
const laneMat=new PBRMaterial('lane_markings',scene); laneMat.albedoColor=new Color3(.55,.58,.52); laneMat.emissiveColor=new Color3(.03,.035,.028); laneMat.roughness=.75;
for(let z=-34;z<=34;z+=8){const dash=MeshBuilder.CreateBox('lane_dash',{width:.12,height:.012,depth:3.2},scene);dash.position.set(0,.012,z);dash.material=laneMat;}
const curbMat=new PBRMaterial('curb_edge',scene); curbMat.albedoColor=new Color3(.12,.14,.15); curbMat.roughness=.82;
for(const x of [-9.3,9.3]){const curb=MeshBuilder.CreateBox('curb',{width:.28,height:.16,depth:80},scene);curb.position.set(x,.08,0);curb.material=curbMat;}
const crosswalkMat=new PBRMaterial('crosswalk_paint',scene); crosswalkMat.albedoColor=new Color3(.72,.74,.7); crosswalkMat.roughness=.8;
for(let i=-4;i<=4;i++){const stripe=MeshBuilder.CreateBox('crosswalk_stripe',{width:1.1,height:.018,depth:.32},scene);stripe.position.set(i*1.65,.026,-1.5);stripe.material=crosswalkMat;}
const planterMat=new PBRMaterial('planter_concrete',scene); planterMat.albedoColor=new Color3(.16,.18,.18); planterMat.roughness=.92;
const trunkMat=new PBRMaterial('tree_trunk',scene); trunkMat.albedoColor=new Color3(.09,.045,.025); trunkMat.roughness=.95;
const leafMat=new PBRMaterial('tree_leaves',scene); leafMat.albedoColor=new Color3(.035,.16,.09); leafMat.roughness=.85;
if(quality!=='mobile')for(const z of [-24,0,24]){for(const x of [-10.8,10.8]){const planter=MeshBuilder.CreateBox('planter',{width:1.15,height:.55,depth:1.15},scene);planter.position.set(x,.28,z);planter.material=planterMat;const trunk=MeshBuilder.CreateCylinder('tree_trunk',{height:2.5,diameter:.16},scene);trunk.position.set(x,.55,z);trunk.material=trunkMat;for(const offset of [[0,1.9,0],[-.35,1.65,0],[.35,1.65,0]]){const crown=MeshBuilder.CreateSphere('tree_crown',{diameter:1.35,segments:12},scene);crown.position.set(x+offset[0],offset[1],z+offset[2]);crown.material=leafMat;}}}
const buildingMat=new PBRMaterial('building',scene); buildingMat.albedoColor=new Color3(.12,.15,.18); buildingMat.metallic=.12; buildingMat.roughness=.62; const rooftopMat=new PBRMaterial('rooftop_unit',scene); rooftopMat.albedoColor=new Color3(.055,.065,.07); rooftopMat.metallic=.45; rooftopMat.roughness=.5;
if(quality!=='mobile'){const facadeTexture=new DynamicTexture('facade_texture',{width:256,height:256},scene,false);const facadeContext=facadeTexture.getContext();facadeContext.fillStyle='#18212a';facadeContext.fillRect(0,0,256,256);for(let y=12;y<256;y+=28){for(let x=10;x<256;x+=34){facadeContext.fillStyle=(x+y)%3===0?'#28435c':'#222e38';facadeContext.fillRect(x,y,18,12);}}for(let y=0;y<256;y+=64){facadeContext.fillStyle='#10161c';facadeContext.fillRect(0,y,256,3);}facadeTexture.update();buildingMat.albedoTexture=loadMaterialTexture('facade/color.jpg',2.2);buildingMat.bumpTexture=loadMaterialTexture('facade/normal.jpg',2.2);buildingMat.roughnessTexture=loadMaterialTexture('facade/roughness.jpg',2.2);buildingMat.albedoColor=Color3.White();}
const cityBuildings=[];let citySeed=0x4d59524e;const cityRand=()=>{citySeed=(citySeed*1664525+1013904223)>>>0;return citySeed/4294967296;};const buildingPalette=[new Color3(.10,.14,.18),new Color3(.16,.12,.11),new Color3(.12,.17,.19),new Color3(.20,.16,.13),new Color3(.09,.12,.16)];for(let i=-30;i<=30;i+=12){for(const x of [-16,16]){const width=7.2+cityRand()*3.5;const depth=7.6+cityRand()*3.8;const h=8+cityRand()*14;const px=x+(cityRand()-.5)*2.4;const pz=i+(cityRand()-.5)*2.2;const b=MeshBuilder.CreateBox('building',{width,height:h,depth},scene);b.position.set(px,h/2,pz);b.rotation.y=(cityRand()-.5)*.045;const mat=buildingMat.clone(`building_material_${i}_${x}`);mat.albedoColor=buildingPalette[Math.floor(cityRand()*buildingPalette.length)].clone();mat.roughness=.54+cityRand()*.18;b.material=mat;b.receiveShadows=true;if(shadowGenerator)shadowGenerator.addShadowCaster(b);cityBuildings.push({mesh:b,x:px,z:pz,width,depth,height:h});if(quality!=='mobile'&&cityRand()>.28){const roof=MeshBuilder.CreateBox('rooftop_unit',{width:1.2+cityRand()*1.4,height:.55+cityRand()*.7,depth:1.1+cityRand()*1.3},scene);roof.position.set(px+(cityRand()-.5)*2,h+.3,pz+(cityRand()-.5)*2);roof.material=rooftopMat;if(shadowGenerator)shadowGenerator.addShadowCaster(roof);}}}
const windowMat=new PBRMaterial('warm_windows',scene); windowMat.albedoColor=new Color3(.12,.08,.035); windowMat.emissiveColor=new Color3(.55,.22,.045); windowMat.roughness=.3;
const coolWindowMat=new PBRMaterial('cool_windows',scene); coolWindowMat.albedoColor=new Color3(.025,.09,.14); coolWindowMat.emissiveColor=new Color3(.03,.16,.3); coolWindowMat.roughness=.28;
if(qualityConfig.windows)for(const b of cityBuildings){const roadSide=b.x>0?-1:1;const faceX=b.x+roadSide*(b.width/2+.035);const rows=Math.max(1,Math.floor((b.height-2.2)/2.8));for(let row=0;row<rows;row++){for(let col=-1;col<=1;col++){const panel=MeshBuilder.CreateBox('window_panel',{width:.06,height:1.25,depth:1.15},scene);panel.position.set(faceX,2+row*2.8,b.z+col*1.9);panel.material=(row+col+Math.round(b.z))%3===0?windowMat:coolWindowMat;}}}
const storefrontMat=new PBRMaterial('storefront_neon',scene); storefrontMat.albedoColor=new Color3(.06,.02,.09); storefrontMat.emissiveColor=new Color3(.3,.02,.42); storefrontMat.roughness=.35;
for(const z of [-18,6,30]){const sign=MeshBuilder.CreateBox('storefront_sign',{width:5.2,height:.5,depth:.08},scene);sign.position.set(-11.7,3.2,z);sign.material=storefrontMat;}
const balconyMat=new PBRMaterial('balcony_metal',scene);balconyMat.albedoColor=new Color3(.08,.09,.095);balconyMat.metallic=.72;balconyMat.roughness=.38;const signagePalette=[new Color3(.06,.55,.95),new Color3(.9,.22,.08),new Color3(.7,.12,.72),new Color3(.95,.48,.08)];const clutterMat=new PBRMaterial('street_clutter',scene);clutterMat.albedoColor=new Color3(.12,.13,.12);clutterMat.metallic=.35;clutterMat.roughness=.72;for(const b of cityBuildings){const side=b.x>0?-1:1;const faceX=b.x+side*(b.width/2+.04);if(quality!=='mobile'&&b.height>10){const levels=Math.min(3,Math.floor(b.height/5));for(let level=0;level<levels;level++){const y=3.1+level*4.1;const slab=MeshBuilder.CreateBox('balcony_slab',{width:.85,height:.12,depth:2.25},scene);slab.position.set(faceX+side*.42,y,b.z);slab.material=balconyMat;const railTop=MeshBuilder.CreateBox('balcony_rail',{width:.06,height:.72,depth:2.25},scene);railTop.position.set(faceX+side*.86,y+.38,b.z);railTop.material=balconyMat;for(const offset of [-.9,0,.9]){const post=MeshBuilder.CreateBox('balcony_post',{width:.05,height:.72,depth:.05},scene);post.position.set(faceX+side*.86,y+.38,b.z+offset);post.material=balconyMat;}}}if(Math.abs(b.z)%24<4){const sign=MeshBuilder.CreateBox('building_sign',{width:2.6,height:.52,depth:.08},scene);sign.position.set(faceX+side*.08,3.6,b.z+(b.x>0?1.8:-1.8));const signMat=new PBRMaterial(`sign_${b.z}_${b.x}`,scene);signMat.albedoColor=signagePalette[Math.floor(Math.abs(b.z+b.x))%signagePalette.length];signMat.emissiveColor=signMat.albedoColor.scale(.7);signMat.roughness=.3;sign.material=signMat;}}for(const z of [-24,-6,12,30]){const side=z%24===0?-1:1;const x=side*9.95;const bin=MeshBuilder.CreateBox('street_bin',{width:.65,height:.95,depth:.65},scene);bin.position.set(x,.48,z);bin.material=clutterMat;const lid=MeshBuilder.CreateBox('street_bin_lid',{width:.72,height:.08,depth:.72},scene);lid.position.set(x,.98,z);lid.material=balconyMat;for(const offset of [-.65,.65]){const bollard=MeshBuilder.CreateCylinder('bollard',{height:.72,diameter:.12,tessellation:12},scene);bollard.position.set(x+side*.95,.36,z+offset);bollard.material=clutterMat;}const crate=MeshBuilder.CreateBox('delivery_crate',{width:.75,height:.55,depth:.75},scene);crate.position.set(x-side*.75,.28,z+.35);crate.material=clutterMat;}
const benchMat=new PBRMaterial('bench_metal',scene); benchMat.albedoColor=new Color3(.08,.09,.1); benchMat.metallic=.55; benchMat.roughness=.42;
if(quality!=='mobile')for(const z of [-12,12]){const seat=MeshBuilder.CreateBox('bench_seat',{width:1.6,height:.12,depth:.42},scene);seat.position.set(10.65,.72,z);seat.material=benchMat;for(const x of [10.1,11.2]){const leg=MeshBuilder.CreateBox('bench_leg',{width:.08,height:.65,depth:.08},scene);leg.position.set(x,.38,z);leg.material=benchMat;}}
const utilityMat=new PBRMaterial('utility_pole',scene); utilityMat.albedoColor=new Color3(.06,.07,.075); utilityMat.metallic=.45; utilityMat.roughness=.5;
for(const z of [-30,30]){const pole=MeshBuilder.CreateCylinder('utility_pole',{height:7,diameter:.14},scene);pole.position.set(8.7,3.5,z);pole.material=utilityMat;const arm=MeshBuilder.CreateBox('utility_arm',{width:2.2,height:.08,depth:.08},scene);arm.position.set(8.7,6.3,z);arm.material=utilityMat;}
const carMat=new PBRMaterial('vehicle',scene);carMat.albedoColor=new Color3(.035,.16,.28);carMat.metallic=.82;carMat.roughness=.24;
const car=MeshBuilder.CreateBox('vehicle',{width:2.25,height:.7,depth:4.5},scene);car.position.set(0,.7,-6);car.material=carMat;if(shadowGenerator)shadowGenerator.addShadowCaster(car);
const trafficMat=new PBRMaterial('traffic_vehicle',scene); trafficMat.metallic=.72; trafficMat.roughness=.3; const ambientTraffic=[];
for(let i=0;i<(quality==='mobile'?2:5);i++){const traffic=MeshBuilder.CreateBox('ambient_vehicle',{width:1.65,height:.55,depth:3.2},scene);traffic.position.set(i%2===0?-4.2:4.2,.55,14+i*11);traffic.material=trafficMat.clone(`traffic_${i}`);traffic.material.albedoColor=[new Color3(.35,.04,.03),new Color3(.04,.2,.36),new Color3(.45,.3,.04)][i%3];ambientTraffic.push({mesh:traffic,speed:2.2+i*.45,direction:i%2===0?1:-1});}
const glass=new PBRMaterial('glass',scene);glass.albedoColor=new Color3(.02,.035,.045);glass.metallic=.2;glass.roughness=.08;
const cabin=MeshBuilder.CreateBox('cabin',{width:1.75,height:.62,depth:2.15},scene);cabin.position.set(0,1.25,-6);cabin.material=glass;
const chromeMat=new PBRMaterial('vehicle_chrome',scene); chromeMat.albedoColor=new Color3(.22,.28,.32); chromeMat.metallic=.95; chromeMat.roughness=.16;
for(const x of [-.82,.82]){for(const z of [-7.35,-4.65]){const wheel=MeshBuilder.CreateCylinder('wheel',{diameter:.58,height:.24,tessellation:20},scene);wheel.rotation.z=Math.PI/2;wheel.position.set(x,.48,z);wheel.material=chromeMat;}}
const grille=MeshBuilder.CreateBox('front_grille',{width:1.15,height:.22,depth:.06},scene);grille.position.set(0,.73,-8.28);grille.material=chromeMat;
const tailMat=new PBRMaterial('tail_lights',scene);tailMat.albedoColor=new Color3(.45,.015,.01);tailMat.emissiveColor=new Color3(.3,.008,.004);
for(const x of [-.7,.7]){const tail=MeshBuilder.CreateBox('tail_light',{width:.28,height:.18,depth:.05},scene);tail.position.set(x,.88,-3.78);tail.material=tailMat;}
const headlightMat=new PBRMaterial('headlight_glow',scene); headlightMat.emissiveColor=new Color3(1,.82,.48); headlightMat.albedoColor=new Color3(1,.72,.28);
for(const x of [-.72,.72]){const lamp=MeshBuilder.CreateSphere('headlight',{diameter:.18,segments:12},scene);lamp.position.set(x,.86,-8.18);lamp.material=headlightMat;const light=new PointLight('headlight_point',new Vector3(x,.9,-8.28),scene);light.diffuse=new Color3(1,.72,.34);light.specular=new Color3(1,.85,.55);light.range=15;light.intensity=0;}
let heroVehicleRoot=null;const proceduralVehicleNames=new Set(['vehicle','cabin','wheel','front_grille','tail_light','headlight']);async function loadHeroVehicle(){const asset=await window.MakyrenLoadAsset('vehicle',{autoAdd:false});if(!asset.loaded||!asset.container.rootNodes.length)return;asset.container.addAllToScene();const root=asset.container.rootNodes[0];root.name='hero_vehicle_sedan_sports';root.position.set(car.position.x,0,car.position.z);root.rotation.y=Math.PI;root.scaling.setAll(1.55);const trimMat=new PBRMaterial('hero_vehicle_trim',scene);trimMat.albedoColor=new Color3(.035,.045,.055);trimMat.metallic=.92;trimMat.roughness=.18;trimMat.clearCoat.isEnabled=true;trimMat.clearCoat.intensity=.65;const lensMat=new PBRMaterial('hero_vehicle_lenses',scene);lensMat.albedoColor=new Color3(.18,.22,.26);lensMat.emissiveColor=new Color3(.18,.2,.22);lensMat.metallic=.35;lensMat.roughness=.12;for(const x of [-.62,.62]){const mirror=MeshBuilder.CreateBox('hero_side_mirror',{width:.16,height:.12,depth:.28},scene);mirror.position.set(x,.62,-.05);mirror.material=trimMat;mirror.parent=root;const headLens=MeshBuilder.CreateBox('hero_head_lens',{width:.28,height:.12,depth:.04},scene);headLens.position.set(x*.7,.45,-1.48);headLens.material=lensMat;headLens.parent=root;}const belt=MeshBuilder.CreateBox('hero_beltline',{width:1.25,height:.055,depth:2.4},scene);belt.position.y=.55;belt.material=trimMat;belt.parent=root;heroVehicleRoot=root;for(const mesh of scene.meshes)if(proceduralVehicleNames.has(mesh.name))mesh.setEnabled(false);if(shadowGenerator)root.getChildMeshes().forEach(mesh=>shadowGenerator.addShadowCaster(mesh));window.MakyrenHeroVehicle={loaded:true,source:'Kenney Car Kit / sedan-sports.glb',license:'CC0',detailLayer:'PBR trim, lenses, side mirrors, beltline'};}
loadHeroVehicle().catch(error=>console.warn('Hero vehicle GLB failed; procedural vehicle remains active.',error));
const streetLights=[];const lampMat=new PBRMaterial('street_lamp_glow',scene);lampMat.emissiveColor=new Color3(1,.46,.12);lampMat.albedoColor=new Color3(.8,.25,.04);
for(let z=-30;z<=30;z+=12){const x=z%24===0?-8.5:8.5;const pole=MeshBuilder.CreateCylinder('street_lamp_pole',{height:4.7,diameter:.09},scene);pole.position.set(x,2.35,z);pole.material=buildingMat;const bulb=MeshBuilder.CreateSphere('street_lamp_bulb',{diameter:.22,segments:12},scene);bulb.position.set(x,4.75,z);bulb.material=lampMat;const light=new SpotLight('street_lamp',new Vector3(x,4.65,z),new Vector3(0,-1,0),Math.PI/2.1,2.2,scene);light.diffuse=new Color3(1,.35,.08);light.specular=new Color3(1,.55,.18);light.range=12;light.intensity=0;streetLights.push({light,bulb,pole});}
async function loadRealisticStreetLamps(){const asset=await window.MakyrenLoadAsset('streetLamp',{autoAdd:false});if(!asset.loaded||!asset.container.rootNodes.length)return;asset.container.addAllToScene();const template=asset.container.rootNodes[0];template.name='street_lamp_01_template';template.setEnabled(false);for(const {light,bulb,pole} of streetLights){pole.setEnabled(false);bulb.setEnabled(false);}streetLights.forEach(({light},index)=>{const root=index===0?template:template.clone(`street_lamp_01_${index}`,null,false);root.setEnabled(true);root.position.set(streetLights[index].light.position.x,0,streetLights[index].light.position.z);root.scaling.setAll(quality==='mobile'?.92:1);if(shadowGenerator)root.getChildMeshes().forEach(mesh=>shadowGenerator.addShadowCaster(mesh));});window.MakyrenRealisticStreetLamps={loaded:true,count:streetLights.length,source:'Poly Haven Street Lamp 01'};}
loadRealisticStreetLamps().catch(error=>console.warn('Street lamp GLB failed; procedural lamps remain active.',error));
const clock={hour:19.25,speed:.045};const formatTime=hour=>{const h=Math.floor(hour)%24;const m=Math.floor((hour-Math.floor(hour))*60);return `${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}`;};
function updateLighting(dt){clock.hour=(clock.hour+dt*clock.speed)%24;const sunAngle=((clock.hour-6)/12)*Math.PI;const daylight=Math.max(0,Math.sin(sunAngle));const night=clock.hour<6||clock.hour>=19;sun.intensity=.4+daylight*2.15;skyLight.intensity=.68+daylight*.82;heroKey.intensity=night?1.8:(quality==='mobile'?1.1:2.2);scene.clearColor=new Color4(.006+daylight*.028,.012+daylight*.04,.028+daylight*.07,1);for(const {light,bulb} of streetLights){light.intensity=night?1.9:0;bulb.visibility=night?1:.35;}for(const light of scene.lights.filter(entry=>entry.name==='headlight_point'))light.intensity=night?1.7:0;const hud=document.getElementById('hud');if(hud)hud.innerHTML=`MA'KYREN • VISUAL-004<br><small>${night?'Night lighting active':'Day lighting active'} • ${formatTime(clock.hour)} • ${quality} tier</small>`;}
const playerRoot=new TransformNode('player_root',scene); playerRoot.position.set(0,0,2);
const playerMat=new PBRMaterial('makyren_skin',scene);playerMat.albedoColor=new Color3(.48,.27,.17);playerMat.roughness=.58;
const shirtMat=new PBRMaterial('makyren_clothes',scene);shirtMat.albedoColor=new Color3(.025,.03,.04);shirtMat.roughness=.72;
const body=MeshBuilder.CreateCapsule('makyren',{height:2.2,radius:.42},scene);body.position.set(0,1.3,0);body.material=shirtMat;if(shadowGenerator)shadowGenerator.addShadowCaster(body);
const head=MeshBuilder.CreateSphere('makyren_head',{diameter:0.82,segments:32},scene);head.position.set(0,2.72,0);head.material=playerMat;
const hair=MeshBuilder.CreateSphere('makyren_hair',{diameter:.86,segments:32},scene);hair.scaling.y=.55;hair.position.set(0,3.02,0);const hairMat=new PBRMaterial('hair',scene);hairMat.albedoColor=new Color3(.018,.012,.01);hairMat.roughness=.82;hair.material=hairMat; body.parent=playerRoot; head.parent=playerRoot; hair.parent=playerRoot;const limbMat=shirtMat;const leftLeg=MeshBuilder.CreateCapsule('left_leg',{height:1.15,radius:.16},scene);const rightLeg=MeshBuilder.CreateCapsule('right_leg',{height:1.15,radius:.16},scene);leftLeg.position.set(-.2,.72,0);rightLeg.position.set(.2,.72,0);leftLeg.material=limbMat;rightLeg.material=limbMat;leftLeg.parent=playerRoot;rightLeg.parent=playerRoot;const leftArm=MeshBuilder.CreateCapsule('left_arm',{height:1.05,radius:.14},scene);const rightArm=MeshBuilder.CreateCapsule('right_arm',{height:1.05,radius:.14},scene);leftArm.position.set(-.55,1.92,0);rightArm.position.set(.55,1.92,0);leftArm.material=limbMat;rightArm.material=limbMat;leftArm.parent=playerRoot;rightArm.parent=playerRoot;for(const mesh of [leftLeg,rightLeg,leftArm,rightArm])if(shadowGenerator)shadowGenerator.addShadowCaster(mesh);const characterAnimator={state:'idle',phase:0,update(dt,moving,sprinting){const next=moving?(sprinting?'sprint':'walk'):'idle';if(next!==this.state){this.state=next;this.phase=0;}this.phase+=dt*(moving?(sprinting?11:8):2.2);const swing=moving?Math.sin(this.phase)*(sprinting?.62:.42):Math.sin(this.phase)*.025;leftLeg.rotation.x=swing;rightLeg.rotation.x=-swing;leftArm.rotation.x=-swing*.8;rightArm.rotation.x=swing*.8;const bob=moving?Math.abs(Math.sin(this.phase))*.045:Math.sin(this.phase)*.012;body.position.y=1.3+bob;head.position.y=2.72+bob*1.5;hair.position.y=3.02+bob*1.5;body.rotation.z=moving?Math.sin(this.phase*.5)*.018:0;}};window.MakyrenCharacterAnimator=characterAnimator;
const keys=new Set(); let vehicleMode=false; let eLatch=false; let playerYaw=0; let touchMove={x:0,y:0}; const worldBounds={x:8.2,z:34}; const mission={id:'first_block',state:'approach',checkpointZ:-22}; const markerMat=new PBRMaterial('mission_marker',scene); markerMat.albedoColor=new Color3(.2,.03,.35); markerMat.emissiveColor=new Color3(.7,.04,1); const checkpointMarker=MeshBuilder.CreateTorus('mission_checkpoint',{diameter:3.2,thickness:.14,tessellation:32},scene); checkpointMarker.position.set(0,.12,mission.checkpointZ); checkpointMarker.rotation.x=Math.PI/2; checkpointMarker.material=markerMat; checkpointMarker.setEnabled(false); try{const saved=JSON.parse(localStorage.getItem('makyren-visual-mission')||'null');if(saved?.id===mission.id)mission.state=saved.state||mission.state;}catch{} window.MakyrenMission=mission; const saveMission=()=>{try{localStorage.setItem('makyren-visual-mission',JSON.stringify(mission));}catch{}};
addEventListener('keydown',event=>{keys.add(event.code);}); addEventListener('keyup',event=>{keys.delete(event.code);});
function makeTouchControls(){if(!('ontouchstart' in window)&&innerWidth>720)return;const pad=document.createElement('div');pad.id='touch-controls';pad.style.cssText='position:fixed;left:14px;bottom:18px;z-index:8;display:grid;grid-template-columns:48px 48px 48px;grid-template-rows:48px 48px;gap:6px;touch-action:none;';const buttons=[['',0,0],['▲',1,0],['',2,0],['◀',0,1],['▼',1,1],['▶',2,1]];for(const [label,col,row] of buttons){const button=document.createElement('button');button.textContent=label;button.style.cssText='border:1px solid #ffffff44;border-radius:12px;background:#07101dcc;color:#fff;font-size:20px;font-weight:800;';if(label){const code=label==='▲'?'KeyW':label==='▼'?'KeyS':label==='◀'?'KeyA':'KeyD';button.addEventListener('pointerdown',()=>keys.add(code));button.addEventListener('pointerup',()=>keys.delete(code));button.addEventListener('pointercancel',()=>keys.delete(code));}button.style.gridColumn=String(col+1);button.style.gridRow=String(row+1);pad.appendChild(button);}document.body.appendChild(pad);}
makeTouchControls();
const perfHud=debug?document.createElement('div'):null; if(perfHud){perfHud.id='perf-hud';perfHud.style.cssText='position:fixed;right:14px;top:14px;z-index:9;padding:7px 9px;border:1px solid #ffffff22;border-radius:8px;background:#07101dcc;color:#9ff;font:11px monospace;pointer-events:none;';perfHud.textContent='PERF';document.body.appendChild(perfHud);}
let perfClock=0;let ssrGuardClock=0;function updatePerformance(dt){perfClock+=dt;ssrGuardClock+=dt;if(perfHud&&perfClock>.5){perfClock=0;const fps=Math.round(engine.getFps());const active=scene.getActiveMeshes().length;const total=scene.meshes.length;perfHud.textContent=`${quality.toUpperCase()} | FPS ${fps} | ACTIVE ${active}/${total}`;window.MakyrenPerf={fps,activeMeshes:active,totalMeshes:total,quality,ssr:ssr?.isEnabled??false};}if(ssr&&ssrGuardClock>2){ssrGuardClock=0;const fps=engine.getFps();if(fps>0&&fps<24&&ssr.isEnabled){ssr.isEnabled=false;window.MakyrenPostFX.ssrFallback='disabled_below_24fps';}}}
function updateGameplay(dt){const forward=(keys.has('KeyW')||keys.has('ArrowUp')?1:0)-(keys.has('KeyS')||keys.has('ArrowDown')?1:0);const strafe=(keys.has('KeyD')||keys.has('ArrowRight')?1:0)-(keys.has('KeyA')||keys.has('ArrowLeft')?1:0);const sprint=keys.has('ShiftLeft')||keys.has('ShiftRight');const speed=(sprint?7:4.2)*dt;const distance=Math.hypot(car.position.x-playerRoot.position.x,car.position.z-playerRoot.position.z);if(keys.has('KeyE')&&!eLatch&&distance<5){vehicleMode=!vehicleMode;playerRoot.setEnabled(!vehicleMode);if(vehicleMode&&mission.state==='approach')mission.state='drive';saveMission();eLatch=true;}if(!keys.has('KeyE'))eLatch=false;if(keys.has('KeyR')){vehicleMode=false;playerRoot.setEnabled(true);playerRoot.position.set(0,0,2);car.position.set(0,.7,-6);mission.state='approach';saveMission();}const moveX=strafe*speed,moveZ=forward*speed;characterAnimator.update(dt,Boolean((forward||strafe)&&!vehicleMode),sprint);if(forward||strafe){if(vehicleMode){car.position.x+=moveX;car.position.z+=moveZ;car.rotation.y=Math.atan2(moveX,moveZ)+Math.PI;if(heroVehicleRoot){heroVehicleRoot.position.x=car.position.x;heroVehicleRoot.position.z=car.position.z;heroVehicleRoot.rotation.y=car.rotation.y;}}else{playerRoot.position.x+=moveX;playerRoot.position.z+=moveZ;playerYaw=Math.atan2(moveX,moveZ);playerRoot.rotation.y=playerYaw;}}if(mission.state==='drive'&&car.position.z<=mission.checkpointZ){mission.state='complete';saveMission();}checkpointMarker.setEnabled(mission.state==='drive');if(mission.state==='drive'){checkpointMarker.rotation.z+=dt*1.8;const pulse=1+Math.sin(performance.now()*.006)*.08;checkpointMarker.scaling.set(pulse, pulse, pulse);}for(const traffic of ambientTraffic){traffic.mesh.position.z+=traffic.speed*traffic.direction*dt;if(traffic.mesh.position.z>35)traffic.mesh.position.z=-35;if(traffic.mesh.position.z<-35)traffic.mesh.position.z=35;}if(vehicleMode){car.position.x=Math.max(-worldBounds.x,Math.min(worldBounds.x,car.position.x));car.position.z=Math.max(-worldBounds.z,Math.min(worldBounds.z,car.position.z));if(heroVehicleRoot){heroVehicleRoot.position.x=car.position.x;heroVehicleRoot.position.z=car.position.z;heroVehicleRoot.rotation.y=car.rotation.y;}}else{playerRoot.position.x=Math.max(-worldBounds.x,Math.min(worldBounds.x,playerRoot.position.x));playerRoot.position.z=Math.max(-worldBounds.z,Math.min(worldBounds.z,playerRoot.position.z));if(forward||strafe)body.rotation.y=Math.sin(performance.now()*.012)*.035;}
const focus=vehicleMode?car.position:playerRoot.position;const cameraFollow=Math.min(1,dt*7);camera.target.x+=(focus.x-camera.target.x)*cameraFollow;camera.target.y+=(.92-camera.target.y)*cameraFollow;camera.target.z+=(focus.z-camera.target.z)*cameraFollow;const objective=mission.state==='approach'?'Reach the blue vehicle':mission.state==='drive'?'Drive to the north checkpoint':'Block secured • press R to replay';const hud=document.getElementById('hud');if(hud){const prompt=!vehicleMode&&distance<5?' • E enter vehicle':vehicleMode?' • E exit vehicle':'';hud.innerHTML=`MA'KYREN • VISUAL-004<br><small>${objective} • ${formatTime(clock.hour)} • ${quality} tier • WASD/Arrows move${prompt} • R reset</small>`;}}
scene.environmentTexture=null; scene.render();
let previousTime=performance.now();engine.runRenderLoop(()=>{const now=performance.now();const dt=Math.min(.1,(now-previousTime)/1000);previousTime=now;updateLighting(dt);updateGameplay(dt);updatePerformance(dt);scene.render();});
addEventListener('resize',()=>engine.resize());
window.MakyrenScene=scene; window.__MAKYREN_VISUAL_READY__=true;