import { Engine, Scene, ArcRotateCamera, Vector3, TransformNode, HemisphericLight, DirectionalLight, PointLight, Color4, MeshBuilder, StandardMaterial, Color3, PBRMaterial, Texture, GlowLayer } from '@babylonjs/core';
import '@babylonjs/loaders/glTF';
import { SceneLoader } from '@babylonjs/core/Loading/sceneLoader';
import { DynamicTexture } from '@babylonjs/core/Materials/Textures/dynamicTexture';

const canvas=document.getElementById('renderCanvas');
const params=new URLSearchParams(location.search); const qualityParam=params.get('quality'); const debug=params.get('debug')==='1';
const quality=qualityParam||((innerWidth<720||navigator.hardwareConcurrency<4)?'mobile':'high');
const qualityConfig={mobile:{scale:1.55,glow:.25,windows:false},medium:{scale:1.2,glow:.45,windows:true},high:{scale:.85,glow:.7,windows:true}}[quality]||{scale:.85,glow:.7,windows:true};
const engine=new Engine(canvas,true,{preserveDrawingBuffer:false,stencil:true},true); engine.setHardwareScalingLevel(qualityConfig.scale);
window.MakyrenVisualQuality={preset:quality,config:qualityConfig};
window.MakyrenAssetSlots={character:'assets/makyren.glb',vehicle:'assets/city_vehicle.glb',buildings:'assets/city-kit.glb',props:'assets/street-props.glb'};
window.MakyrenLoadAsset=async slot=>{const path=window.MakyrenAssetSlots[slot];if(!path)throw new Error(`Unknown asset slot: ${slot}`);try{const container=await SceneLoader.LoadAssetContainerAsync('',path,scene);container.addAllToScene();return {slot,path,container,loaded:true};}catch(error){console.warn(`Optional asset ${slot} unavailable; procedural fallback remains active.`,error);return {slot,path,loaded:false,fallback:true};}};
const scene=new Scene(engine); scene.clearColor=new Color4(.018,.028,.05,1); scene.fogMode=Scene.FOGMODE_EXP2; scene.fogDensity=quality==='mobile'?.014:.008; scene.fogColor=new Color3(.018,.028,.05); const glow=new GlowLayer('cinematic_glow',scene); glow.intensity=qualityConfig.glow;
const camera=new ArcRotateCamera('camera',-Math.PI/2.5,1.18,30,new Vector3(0,1.8,0),scene);
camera.attachControl(canvas,true); camera.wheelPrecision=80; camera.lowerRadiusLimit=6; camera.upperRadiusLimit=45; camera.minZ=.1; scene.activeCamera=camera;
const skyLight=new HemisphericLight('sky',new Vector3(0,1,0),scene); skyLight.intensity=1.25;
const sun=new DirectionalLight('sun',new Vector3(-0.45,-1,0.35),scene); sun.intensity=2.6; sun.position=new Vector3(30,45,-25);
const road=MeshBuilder.CreateGround('road',{width:18,height:80},scene);
const roadMat=new PBRMaterial('asphalt',scene); roadMat.albedoColor=new Color3(.045,.052,.058); roadMat.roughness=.88; road.material=roadMat;
const sidewalkMat=new PBRMaterial('sidewalk',scene); sidewalkMat.albedoColor=new Color3(.24,.25,.24); sidewalkMat.roughness=.9;
for(const x of [-11,11]){const s=MeshBuilder.CreateGround('sidewalk',{width:4,height:80},scene);s.position.x=x;s.material=sidewalkMat;}
const laneMat=new PBRMaterial('lane_markings',scene); laneMat.albedoColor=new Color3(.55,.58,.52); laneMat.emissiveColor=new Color3(.03,.035,.028); laneMat.roughness=.75;
for(let z=-34;z<=34;z+=8){const dash=MeshBuilder.CreateBox('lane_dash',{width:.12,height:.012,depth:3.2},scene);dash.position.set(0,.012,z);dash.material=laneMat;}
const curbMat=new PBRMaterial('curb_edge',scene); curbMat.albedoColor=new Color3(.12,.14,.15); curbMat.roughness=.82;
for(const x of [-9.3,9.3]){const curb=MeshBuilder.CreateBox('curb',{width:.28,height:.16,depth:80},scene);curb.position.set(x,.08,0);curb.material=curbMat;}
const crosswalkMat=new PBRMaterial('crosswalk_paint',scene); crosswalkMat.albedoColor=new Color3(.72,.74,.7); crosswalkMat.roughness=.8;
for(let i=-4;i<=4;i++){const stripe=MeshBuilder.CreateBox('crosswalk_stripe',{width:1.1,height:.018,depth:.32},scene);stripe.position.set(i*1.65,.026,-1.5);stripe.material=crosswalkMat;}
const planterMat=new PBRMaterial('planter_concrete',scene); planterMat.albedoColor=new Color3(.16,.18,.18); planterMat.roughness=.92;
const trunkMat=new PBRMaterial('tree_trunk',scene); trunkMat.albedoColor=new Color3(.09,.045,.025); trunkMat.roughness=.95;
const leafMat=new PBRMaterial('tree_leaves',scene); leafMat.albedoColor=new Color3(.035,.16,.09); leafMat.roughness=.85;
if(quality!=='mobile')for(const z of [-24,0,24]){for(const x of [-10.8,10.8]){const planter=MeshBuilder.CreateBox('planter',{width:1.15,height:.55,depth:1.15},scene);planter.position.set(x,.28,z);planter.material=planterMat;const trunk=MeshBuilder.CreateCylinder('tree_trunk',{height:2.5,diameter:.16},scene);trunk.position.set(x,.55,z);trunk.material=trunkMat;for(const offset of [[0,1.9,0],[-.35,1.65,0],[.35,1.65,0]]){const crown=MeshBuilder.CreateSphere('tree_crown',{diameter:1.35,segments:12},scene);crown.position.set(x+offset[0],offset[1],z+offset[2]);crown.material=leafMat;}}}
const buildingMat=new PBRMaterial('building',scene); buildingMat.albedoColor=new Color3(.12,.15,.18); buildingMat.metallic=.12; buildingMat.roughness=.62;
if(quality!=='mobile'){const facadeTexture=new DynamicTexture('facade_texture',{width:256,height:256},scene,false);const facadeContext=facadeTexture.getContext();facadeContext.fillStyle='#18212a';facadeContext.fillRect(0,0,256,256);for(let y=12;y<256;y+=28){for(let x=10;x<256;x+=34){facadeContext.fillStyle=(x+y)%3===0?'#28435c':'#222e38';facadeContext.fillRect(x,y,18,12);}}for(let y=0;y<256;y+=64){facadeContext.fillStyle='#10161c';facadeContext.fillRect(0,y,256,3);}facadeTexture.update();buildingMat.albedoTexture=facadeTexture;buildingMat.albedoColor=Color3.White();}
for(let i=-30;i<=30;i+=12){for(const x of [-16,16]){const h=8+(Math.abs(i)%20);const b=MeshBuilder.CreateBox('building',{width:8,height:h,depth:9},scene);b.position.set(x,h/2,i);b.material=buildingMat;}}
const windowMat=new PBRMaterial('warm_windows',scene); windowMat.albedoColor=new Color3(.12,.08,.035); windowMat.emissiveColor=new Color3(.55,.22,.045); windowMat.roughness=.3;
const coolWindowMat=new PBRMaterial('cool_windows',scene); coolWindowMat.albedoColor=new Color3(.025,.09,.14); coolWindowMat.emissiveColor=new Color3(.03,.16,.3); coolWindowMat.roughness=.28;
if(qualityConfig.windows)for(let z=-30;z<=30;z+=12){for(const x of [-11.93,11.93]){const h=8+(Math.abs(z)%20);for(let y=3;y<h-.8;y+=3.1){const panel=MeshBuilder.CreateBox('window_panel',{width:.06,height:1.35,depth:1.65},scene);panel.position.set(x,y,z+(z%24===0?1.8:-1.8));panel.material=(z/12)%2===0?windowMat:coolWindowMat;}}}
const storefrontMat=new PBRMaterial('storefront_neon',scene); storefrontMat.albedoColor=new Color3(.06,.02,.09); storefrontMat.emissiveColor=new Color3(.3,.02,.42); storefrontMat.roughness=.35;
for(const z of [-18,6,30]){const sign=MeshBuilder.CreateBox('storefront_sign',{width:5.2,height:.5,depth:.08},scene);sign.position.set(-11.7,3.2,z);sign.material=storefrontMat;}
const benchMat=new PBRMaterial('bench_metal',scene); benchMat.albedoColor=new Color3(.08,.09,.1); benchMat.metallic=.55; benchMat.roughness=.42;
if(quality!=='mobile')for(const z of [-12,12]){const seat=MeshBuilder.CreateBox('bench_seat',{width:1.6,height:.12,depth:.42},scene);seat.position.set(10.65,.72,z);seat.material=benchMat;for(const x of [10.1,11.2]){const leg=MeshBuilder.CreateBox('bench_leg',{width:.08,height:.65,depth:.08},scene);leg.position.set(x,.38,z);leg.material=benchMat;}}
const utilityMat=new PBRMaterial('utility_pole',scene); utilityMat.albedoColor=new Color3(.06,.07,.075); utilityMat.metallic=.45; utilityMat.roughness=.5;
for(const z of [-30,30]){const pole=MeshBuilder.CreateCylinder('utility_pole',{height:7,diameter:.14},scene);pole.position.set(8.7,3.5,z);pole.material=utilityMat;const arm=MeshBuilder.CreateBox('utility_arm',{width:2.2,height:.08,depth:.08},scene);arm.position.set(8.7,6.3,z);arm.material=utilityMat;}
const carMat=new PBRMaterial('vehicle',scene);carMat.albedoColor=new Color3(.035,.16,.28);carMat.metallic=.82;carMat.roughness=.24;
const car=MeshBuilder.CreateBox('vehicle',{width:2.25,height:.7,depth:4.5},scene);car.position.set(0,.7,-6);car.material=carMat;
const trafficMat=new PBRMaterial('traffic_vehicle',scene); trafficMat.metallic=.72; trafficMat.roughness=.3; const ambientTraffic=[];
for(let i=0;i<(quality==='mobile'?2:5);i++){const traffic=MeshBuilder.CreateBox('ambient_vehicle',{width:1.65,height:.55,depth:3.2},scene);traffic.position.set(i%2===0?-4.2:4.2,.55,14+i*11);traffic.material=trafficMat.clone(`traffic_${i}`);traffic.material.albedoColor=[new Color3(.35,.04,.03),new Color3(.04,.2,.36),new Color3(.45,.3,.04)][i%3];ambientTraffic.push({mesh:traffic,speed:2.2+i*.45,direction:i%2===0?1:-1});}
const glass=new PBRMaterial('glass',scene);glass.albedoColor=new Color3(.02,.035,.045);glass.metallic=.2;glass.roughness=.08;
const cabin=MeshBuilder.CreateBox('cabin',{width:1.75,height:.62,depth:2.15},scene);cabin.position.set(0,1.25,-6);cabin.material=glass;
const chromeMat=new PBRMaterial('vehicle_chrome',scene); chromeMat.albedoColor=new Color3(.22,.28,.32); chromeMat.metallic=.95; chromeMat.roughness=.16;
for(const x of [-.82,.82]){for(const z of [-7.35,-4.65]){const wheel=MeshBuilder.CreateCylinder('wheel',{diameter:.58,height:.24,tessellation:20},scene);wheel.rotation.z=Math.PI/2;wheel.position.set(x,.48,z);wheel.material=chromeMat;}}
const grille=MeshBuilder.CreateBox('front_grille',{width:1.15,height:.22,depth:.06},scene);grille.position.set(0,.73,-8.28);grille.material=chromeMat;
const tailMat=new PBRMaterial('tail_lights',scene);tailMat.albedoColor=new Color3(.45,.015,.01);tailMat.emissiveColor=new Color3(.3,.008,.004);
for(const x of [-.7,.7]){const tail=MeshBuilder.CreateBox('tail_light',{width:.28,height:.18,depth:.05},scene);tail.position.set(x,.88,-3.78);tail.material=tailMat;}
const headlightMat=new PBRMaterial('headlight_glow',scene); headlightMat.emissiveColor=new Color3(1,.82,.48); headlightMat.albedoColor=new Color3(1,.72,.28);
for(const x of [-.72,.72]){const lamp=MeshBuilder.CreateSphere('headlight',{diameter:.18,segments:12},scene);lamp.position.set(x,.86,-8.18);lamp.material=headlightMat;const light=new PointLight('headlight_point',new Vector3(x,.9,-8.28),scene);light.diffuse=new Color3(1,.72,.34);light.specular=new Color3(1,.85,.55);light.range=15;light.intensity=0;}
const streetLights=[];const lampMat=new PBRMaterial('street_lamp_glow',scene);lampMat.emissiveColor=new Color3(1,.46,.12);lampMat.albedoColor=new Color3(.8,.25,.04);
for(let z=-30;z<=30;z+=12){const x=z%24===0?-8.5:8.5;const pole=MeshBuilder.CreateCylinder('street_lamp_pole',{height:4.7,diameter:.09},scene);pole.position.set(x,2.35,z);pole.material=buildingMat;const bulb=MeshBuilder.CreateSphere('street_lamp_bulb',{diameter:.22,segments:12},scene);bulb.position.set(x,4.75,z);bulb.material=lampMat;const light=new PointLight('street_lamp',new Vector3(x,4.65,z),scene);light.diffuse=new Color3(1,.35,.08);light.specular=new Color3(1,.55,.18);light.range=11;light.intensity=0;streetLights.push({light,bulb});}
const clock={hour:16.5,speed:.045};const formatTime=hour=>{const h=Math.floor(hour)%24;const m=Math.floor((hour-Math.floor(hour))*60);return `${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}`;};
function updateLighting(dt){clock.hour=(clock.hour+dt*clock.speed)%24;const sunAngle=((clock.hour-6)/12)*Math.PI;const daylight=Math.max(0,Math.sin(sunAngle));const night=clock.hour<6||clock.hour>=19;sun.intensity=.35+daylight*2.25;skyLight.intensity=.42+daylight*.9;scene.clearColor=new Color4(.012+daylight*.023,.018+daylight*.037,.035+daylight*.04,1);for(const {light,bulb} of streetLights){light.intensity=night?1.9:0;bulb.visibility=night?1:.35;}for(const light of scene.lights.filter(entry=>entry.name==='headlight_point'))light.intensity=night?1.7:0;const hud=document.getElementById('hud');if(hud)hud.innerHTML=`MA'KYREN • VISUAL-004<br><small>${night?'Night lighting active':'Day lighting active'} • ${formatTime(clock.hour)} • ${quality} tier</small>`;}
const playerRoot=new TransformNode('player_root',scene); playerRoot.position.set(0,0,2);
const playerMat=new PBRMaterial('makyren_skin',scene);playerMat.albedoColor=new Color3(.48,.27,.17);playerMat.roughness=.58;
const shirtMat=new PBRMaterial('makyren_clothes',scene);shirtMat.albedoColor=new Color3(.025,.03,.04);shirtMat.roughness=.72;
const body=MeshBuilder.CreateCapsule('makyren',{height:2.2,radius:.42},scene);body.position.set(0,1.3,0);body.material=shirtMat;
const head=MeshBuilder.CreateSphere('makyren_head',{diameter:0.82,segments:32},scene);head.position.set(0,2.72,0);head.material=playerMat;
const hair=MeshBuilder.CreateSphere('makyren_hair',{diameter:.86,segments:32},scene);hair.scaling.y=.55;hair.position.set(0,3.02,0);const hairMat=new PBRMaterial('hair',scene);hairMat.albedoColor=new Color3(.018,.012,.01);hairMat.roughness=.82;hair.material=hairMat; body.parent=playerRoot; head.parent=playerRoot; hair.parent=playerRoot;
const keys=new Set(); let vehicleMode=false; let eLatch=false; let playerYaw=0; let touchMove={x:0,y:0}; const worldBounds={x:8.2,z:34}; const mission={id:'first_block',state:'approach',checkpointZ:-22}; const markerMat=new PBRMaterial('mission_marker',scene); markerMat.albedoColor=new Color3(.2,.03,.35); markerMat.emissiveColor=new Color3(.7,.04,1); const checkpointMarker=MeshBuilder.CreateTorus('mission_checkpoint',{diameter:3.2,thickness:.14,tessellation:32},scene); checkpointMarker.position.set(0,.12,mission.checkpointZ); checkpointMarker.rotation.x=Math.PI/2; checkpointMarker.material=markerMat; checkpointMarker.setEnabled(false); try{const saved=JSON.parse(localStorage.getItem('makyren-visual-mission')||'null');if(saved?.id===mission.id)mission.state=saved.state||mission.state;}catch{} window.MakyrenMission=mission; const saveMission=()=>{try{localStorage.setItem('makyren-visual-mission',JSON.stringify(mission));}catch{}};
addEventListener('keydown',event=>{keys.add(event.code);}); addEventListener('keyup',event=>{keys.delete(event.code);});
function makeTouchControls(){if(!('ontouchstart' in window)&&innerWidth>720)return;const pad=document.createElement('div');pad.id='touch-controls';pad.style.cssText='position:fixed;left:14px;bottom:18px;z-index:8;display:grid;grid-template-columns:48px 48px 48px;grid-template-rows:48px 48px;gap:6px;touch-action:none;';const buttons=[['',0,0],['▲',1,0],['',2,0],['◀',0,1],['▼',1,1],['▶',2,1]];for(const [label,col,row] of buttons){const button=document.createElement('button');button.textContent=label;button.style.cssText='border:1px solid #ffffff44;border-radius:12px;background:#07101dcc;color:#fff;font-size:20px;font-weight:800;';if(label){const code=label==='▲'?'KeyW':label==='▼'?'KeyS':label==='◀'?'KeyA':'KeyD';button.addEventListener('pointerdown',()=>keys.add(code));button.addEventListener('pointerup',()=>keys.delete(code));button.addEventListener('pointercancel',()=>keys.delete(code));}button.style.gridColumn=String(col+1);button.style.gridRow=String(row+1);pad.appendChild(button);}document.body.appendChild(pad);}
makeTouchControls();
const perfHud=debug?document.createElement('div'):null; if(perfHud){perfHud.id='perf-hud';perfHud.style.cssText='position:fixed;right:14px;top:14px;z-index:9;padding:7px 9px;border:1px solid #ffffff22;border-radius:8px;background:#07101dcc;color:#9ff;font:11px monospace;pointer-events:none;';perfHud.textContent='PERF';document.body.appendChild(perfHud);}
let perfClock=0; function updatePerformance(dt){perfClock+=dt;if(perfHud&&perfClock>.5){perfClock=0;const fps=Math.round(engine.getFps());const active=scene.getActiveMeshes().length;const total=scene.meshes.length;perfHud.textContent=`${quality.toUpperCase()} | FPS ${fps} | ACTIVE ${active}/${total}`;window.MakyrenPerf={fps,activeMeshes:active,totalMeshes:total,quality};}}
function updateGameplay(dt){const forward=(keys.has('KeyW')||keys.has('ArrowUp')?1:0)-(keys.has('KeyS')||keys.has('ArrowDown')?1:0);const strafe=(keys.has('KeyD')||keys.has('ArrowRight')?1:0)-(keys.has('KeyA')||keys.has('ArrowLeft')?1:0);const sprint=keys.has('ShiftLeft')||keys.has('ShiftRight');const speed=(sprint?7:4.2)*dt;const distance=Math.hypot(car.position.x-playerRoot.position.x,car.position.z-playerRoot.position.z);if(keys.has('KeyE')&&!eLatch&&distance<5){vehicleMode=!vehicleMode;playerRoot.setEnabled(!vehicleMode);if(vehicleMode&&mission.state==='approach')mission.state='drive';saveMission();eLatch=true;}if(!keys.has('KeyE'))eLatch=false;if(keys.has('KeyR')){vehicleMode=false;playerRoot.setEnabled(true);playerRoot.position.set(0,0,2);car.position.set(0,.7,-6);mission.state='approach';saveMission();}const moveX=strafe*speed,moveZ=-forward*speed;if(forward||strafe){if(vehicleMode){car.position.x+=moveX;car.position.z+=moveZ;car.rotation.y=Math.atan2(moveX,moveZ);}else{playerRoot.position.x+=moveX;playerRoot.position.z+=moveZ;playerYaw=Math.atan2(moveX,moveZ);playerRoot.rotation.y=playerYaw;}}if(mission.state==='drive'&&car.position.z<=mission.checkpointZ){mission.state='complete';saveMission();}checkpointMarker.setEnabled(mission.state==='drive');if(mission.state==='drive'){checkpointMarker.rotation.z+=dt*1.8;const pulse=1+Math.sin(performance.now()*.006)*.08;checkpointMarker.scaling.set(pulse, pulse, pulse);}for(const traffic of ambientTraffic){traffic.mesh.position.z+=traffic.speed*traffic.direction*dt;if(traffic.mesh.position.z>35)traffic.mesh.position.z=-35;if(traffic.mesh.position.z<-35)traffic.mesh.position.z=35;}if(vehicleMode){car.position.x=Math.max(-worldBounds.x,Math.min(worldBounds.x,car.position.x));car.position.z=Math.max(-worldBounds.z,Math.min(worldBounds.z,car.position.z));}else{playerRoot.position.x=Math.max(-worldBounds.x,Math.min(worldBounds.x,playerRoot.position.x));playerRoot.position.z=Math.max(-worldBounds.z,Math.min(worldBounds.z,playerRoot.position.z));if(forward||strafe)body.rotation.y=Math.sin(performance.now()*.012)*.035;}
const focus=vehicleMode?car.position:playerRoot.position;camera.target.x+=(focus.x-camera.target.x)*Math.min(1,dt*5);camera.target.z+=(focus.z-camera.target.z)*Math.min(1,dt*5);const objective=mission.state==='approach'?'Reach the blue vehicle':mission.state==='drive'?'Drive to the north checkpoint':'Block secured • press R to replay';const hud=document.getElementById('hud');if(hud){const prompt=!vehicleMode&&distance<5?' • E enter vehicle':vehicleMode?' • E exit vehicle':'';hud.innerHTML=`MA'KYREN • VISUAL-004<br><small>${objective} • ${formatTime(clock.hour)} • ${quality} tier • WASD/Arrows move${prompt} • R reset</small>`;}}
scene.environmentTexture=null; scene.render();
let previousTime=performance.now();engine.runRenderLoop(()=>{const now=performance.now();const dt=Math.min(.1,(now-previousTime)/1000);previousTime=now;updateLighting(dt);updateGameplay(dt);updatePerformance(dt);scene.render();});
addEventListener('resize',()=>engine.resize());
window.MakyrenScene=scene; window.__MAKYREN_VISUAL_READY__=true;